# Generated by Django 3.2.5 on 2022-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algos',
            old_name='algos',
            new_name='name'),

        migrations.RenameField(
            model_name='problems',
            old_name='problems',
            new_name='name')
    ]
